import type { Scope } from "@/lib/api/auth";

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface EndpointDoc {
  method: HttpMethod;
  path: string;
  summary: string;
  description?: string;
  tag: string;
  /** Required API-key scope, `public` for unauthenticated, `interactive` for session-only, `admin` for administrators. */
  scope: Scope | "public" | "interactive" | "admin";
  query?: Record<string, string>;
  body?: Record<string, unknown>;
  example?: Record<string, unknown>;
}

const address = { type: "string", description: 'Email address, optionally "Name <address>"' };

/**
 * Single source of truth for the external API surface. Rendered on the in-app API page,
 * exported as OpenAPI at /api/v1/openapi.json and documented in docs/API.md.
 */
export const ENDPOINTS: EndpointDoc[] = [
  {
    method: "GET",
    path: "/api/v1/me",
    summary: "Who am I",
    description: "Returns the authenticated user, role, permissions, authentication method and granted scopes. Use it to verify a key.",
    tag: "Auth",
    scope: "accounts:read",
  },
  {
    method: "PATCH",
    path: "/api/v1/me",
    summary: "Update my profile",
    description: "Name, tour completion and onboarding progress.",
    tag: "Auth",
    scope: "interactive",
    body: {
      type: "object",
      properties: {
        full_name: { type: "string", nullable: true },
        tour_completed: { type: "boolean" },
        onboarding: { type: "object" },
      },
    },
  },
  {
    method: "GET",
    path: "/api/v1/accounts",
    summary: "List connected mailboxes",
    description:
      "Every Gmail and Outlook account connected by the user, with sync status; meta.total gives the count. Several mailboxes may share a display_name, so identify them by email. Tokens are never returned.",
    tag: "Accounts",
    scope: "accounts:read",
  },
  {
    method: "GET",
    path: "/api/v1/accounts/{id}",
    summary: "Get one mailbox",
    tag: "Accounts",
    scope: "accounts:read",
  },
  {
    method: "DELETE",
    path: "/api/v1/accounts/{id}",
    summary: "Disconnect a mailbox",
    description: "Deletes the account and all of its synced emails and events.",
    tag: "Accounts",
    scope: "accounts:write",
  },
  {
    method: "POST",
    path: "/api/v1/accounts/{id}/sync",
    summary: "Sync one mailbox now",
    tag: "Sync",
    scope: "sync:trigger",
  },
  {
    method: "POST",
    path: "/api/v1/sync",
    summary: "Sync all mailboxes now",
    description: "Runs mail + calendar sync for every connected account (or one, if account_id is given) and returns per-account results.",
    tag: "Sync",
    scope: "sync:trigger",
    body: {
      type: "object",
      properties: {
        account_id: { type: "string", format: "uuid" },
        calendar: { type: "boolean", default: true },
        analyze: { type: "boolean", description: "Run AI analysis on new emails (defaults to AI_AUTO_ANALYZE)" },
      },
    },
  },
  {
    method: "GET",
    path: "/api/v1/emails",
    summary: "List / search emails",
    description: "Unified, newest-first list across all mailboxes with full-text search and AI filters. Paginate with limit/offset.",
    tag: "Emails",
    scope: "emails:read",
    query: {
      account_id: "Restrict to one mailbox (uuid)",
      q: "Full-text search over subject, sender and body",
      from: "Sender address/domain contains",
      unread: "true | false",
      starred: "true | false",
      folder: "inbox | sent | archive | drafts | trash | spam",
      category: "AI category, e.g. work, finance, meeting, newsletter",
      priority: "urgent | high | normal | low",
      requires_response: "true | false (AI flag)",
      thread_id: "Provider thread / conversation id",
      since: "ISO 8601 lower bound on received_at",
      until: "ISO 8601 upper bound on received_at",
      limit: "1-100, default 25",
      offset: "default 0",
    },
  },
  {
    method: "GET",
    path: "/api/v1/emails/{id}",
    summary: "Get an email",
    description: "Full headers, text and HTML body, AI analysis (if any) and the other messages in the thread.",
    tag: "Emails",
    scope: "emails:read",
  },
  {
    method: "PATCH",
    path: "/api/v1/emails/{id}",
    summary: "Mark read / starred",
    description: "Updates flags locally and in the mailbox.",
    tag: "Emails",
    scope: "emails:write",
    body: { type: "object", properties: { is_read: { type: "boolean" }, is_starred: { type: "boolean" } } },
    example: { is_read: true },
  },
  {
    method: "POST",
    path: "/api/v1/emails/send",
    summary: "Send a new email",
    tag: "Emails",
    scope: "emails:write",
    body: {
      type: "object",
      required: ["account_id", "to", "subject"],
      properties: {
        account_id: { type: "string", format: "uuid", description: "Mailbox to send from" },
        to: { type: "array", items: address },
        cc: { type: "array", items: address },
        bcc: { type: "array", items: address },
        subject: { type: "string" },
        body_text: { type: "string" },
        body_html: { type: "string" },
      },
    },
    example: {
      account_id: "00000000-0000-0000-0000-000000000000",
      to: ["Jane Doe <jane@example.com>"],
      subject: "Proposal follow-up",
      body_text: "Hi Jane,\n\nFollowing up on the proposal...",
    },
  },
  {
    method: "POST",
    path: "/api/v1/emails/{id}/reply",
    summary: "Reply to an email",
    description: "Replies from the mailbox that received the message, preserving the thread.",
    tag: "Emails",
    scope: "emails:write",
    body: {
      type: "object",
      properties: {
        body_text: { type: "string" },
        body_html: { type: "string" },
        reply_all: { type: "boolean", default: false },
      },
    },
    example: { body_text: "Thanks, confirmed for Tuesday.", reply_all: false },
  },
  {
    method: "POST",
    path: "/api/v1/emails/{id}/analyze",
    summary: "AI-analyse an email",
    description: "Returns category, priority, sentiment, summary, action items, entities and a suggested reply. Cached unless force=true.",
    tag: "AI",
    scope: "ai:use",
    body: { type: "object", properties: { force: { type: "boolean" } } },
  },
  {
    method: "POST",
    path: "/api/v1/ai/analyze",
    summary: "Batch AI analysis",
    description: "Analyses the given email_ids, or the newest un-analysed emails (optionally for one account).",
    tag: "AI",
    scope: "ai:use",
    body: {
      type: "object",
      properties: {
        email_ids: { type: "array", items: { type: "string", format: "uuid" }, maxItems: 50 },
        account_id: { type: "string", format: "uuid" },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 10 },
      },
    },
    example: { limit: 20 },
  },
  {
    method: "POST",
    path: "/api/v1/ai/assistant",
    summary: "Chat with the AI assistant",
    description:
      "Tool-using assistant over all mailboxes and calendars: search/read emails, draft & send replies, schedule meetings, summarise the inbox. Pass conversation_id to continue a thread.",
    tag: "AI",
    scope: "ai:use",
    body: {
      type: "object",
      required: ["message"],
      properties: {
        message: { type: "string" },
        conversation_id: { type: "string", format: "uuid" },
        timezone: { type: "string", description: "IANA timezone used to resolve relative dates" },
      },
    },
    example: { message: "What urgent emails do I have today, and schedule a 30 min call with the sender of the most urgent one tomorrow at 10am?", timezone: "Europe/London" },
  },
  {
    method: "GET",
    path: "/api/v1/ai/conversations",
    summary: "List assistant conversations",
    tag: "AI",
    scope: "ai:use",
  },
  {
    method: "GET",
    path: "/api/v1/ai/conversations/{id}",
    summary: "Get conversation messages",
    tag: "AI",
    scope: "ai:use",
  },
  {
    method: "GET",
    path: "/api/v1/ai/providers",
    summary: "Available LLM providers",
    description: "Supported providers and suggested models, plus whether the platform-hosted AI is available to this user.",
    tag: "AI",
    scope: "ai:use",
  },
  {
    method: "GET",
    path: "/api/v1/ai/integrations",
    summary: "List my AI integrations",
    description: "Bring-your-own LLM keys (Anthropic, OpenAI, Google Gemini, OpenAI-compatible). Keys are never returned.",
    tag: "AI",
    scope: "interactive",
  },
  {
    method: "POST",
    path: "/api/v1/ai/integrations",
    summary: "Add an AI integration",
    tag: "AI",
    scope: "interactive",
    body: {
      type: "object",
      required: ["provider", "model"],
      properties: {
        provider: { type: "string", enum: ["anthropic", "openai", "google", "openai_compatible"] },
        label: { type: "string" },
        model: { type: "string" },
        api_key: { type: "string" },
        base_url: { type: "string", description: "Only for openai_compatible" },
        make_default: { type: "boolean" },
      },
    },
    example: { provider: "openai", model: "gpt-5-mini", api_key: "sk-...", make_default: true },
  },
  {
    method: "PATCH",
    path: "/api/v1/ai/integrations/{id}",
    summary: "Update an AI integration",
    tag: "AI",
    scope: "interactive",
    body: {
      type: "object",
      properties: {
        label: { type: "string" },
        model: { type: "string" },
        api_key: { type: "string" },
        base_url: { type: "string" },
        enabled: { type: "boolean" },
        make_default: { type: "boolean" },
      },
    },
  },
  {
    method: "DELETE",
    path: "/api/v1/ai/integrations/{id}",
    summary: "Remove an AI integration",
    tag: "AI",
    scope: "interactive",
  },
  {
    method: "POST",
    path: "/api/v1/ai/integrations/{id}/test",
    summary: "Test an AI integration",
    description: "Sends a tiny prompt to the provider and records the result.",
    tag: "AI",
    scope: "interactive",
  },
  {
    method: "GET",
    path: "/api/v1/calendar/events",
    summary: "List calendar events",
    description: "Events across all connected calendars in a range (defaults: now to +30 days).",
    tag: "Calendar",
    scope: "calendar:read",
    query: {
      account_id: "Restrict to one mailbox (uuid)",
      from: "ISO 8601 range start",
      to: "ISO 8601 range end",
      limit: "1-500, default 100",
    },
  },
  {
    method: "GET",
    path: "/api/v1/calendar/upcoming",
    summary: "Events starting soon (for reminders)",
    description:
      "Events starting within the next N minutes across all calendars, soonest first, each with minutes_until_start. Pass refresh=true to re-pull the calendars from Google/Microsoft first (needs sync:trigger) so nothing added outside the hub is missed. Poll this every few minutes to drive reminders.",
    tag: "Calendar",
    scope: "calendar:read",
    query: {
      within_minutes: "1-1440, default 60",
      refresh: "true to refresh calendars first (calendar-only sync, a few seconds)",
      include_in_progress: "default true; false hides events that already started",
      account_id: "Restrict to one mailbox (uuid)",
      limit: "1-200, default 50",
    },
  },
  {
    method: "POST",
    path: "/api/v1/calendar/events",
    summary: "Schedule a meeting",
    description: "Creates the event on the chosen account's calendar, invites attendees and (by default) adds a Google Meet / Teams link.",
    tag: "Calendar",
    scope: "calendar:write",
    body: {
      type: "object",
      required: ["account_id", "title", "start", "end"],
      properties: {
        account_id: { type: "string", format: "uuid" },
        title: { type: "string" },
        description: { type: "string" },
        location: { type: "string" },
        start: { type: "string", format: "date-time" },
        end: { type: "string", format: "date-time" },
        timezone: { type: "string", default: "UTC" },
        attendees: { type: "array", items: address },
        online_meeting: { type: "boolean", default: true },
        all_day: { type: "boolean", default: false },
      },
    },
    example: {
      account_id: "00000000-0000-0000-0000-000000000000",
      title: "Project kickoff",
      start: "2026-09-15T10:00:00+01:00",
      end: "2026-09-15T10:30:00+01:00",
      timezone: "Europe/London",
      attendees: ["jane@example.com"],
      online_meeting: true,
    },
  },
  {
    method: "DELETE",
    path: "/api/v1/calendar/events/{id}",
    summary: "Cancel a meeting",
    tag: "Calendar",
    scope: "calendar:write",
  },
  {
    method: "GET",
    path: "/api/v1/analytics/summary",
    summary: "Analytics summary",
    description: "Totals, AI category/priority/sentiment breakdowns, daily volume, top senders and per-account stats.",
    tag: "Analytics",
    scope: "analytics:read",
    query: { days: "Period in days, 1-365 (default 30)" },
  },
  {
    method: "GET",
    path: "/api/v1/api-keys",
    summary: "List API keys",
    tag: "API keys",
    scope: "interactive",
  },
  {
    method: "POST",
    path: "/api/v1/api-keys",
    summary: "Create an API key",
    description: "The full key is returned once. Store it securely - only a hash is kept.",
    tag: "API keys",
    scope: "interactive",
    body: {
      type: "object",
      required: ["name"],
      properties: {
        name: { type: "string" },
        scopes: { type: "array", items: { type: "string" } },
        expires_in_days: { type: "integer", nullable: true },
      },
    },
  },
  {
    method: "DELETE",
    path: "/api/v1/api-keys/{id}",
    summary: "Revoke an API key",
    tag: "API keys",
    scope: "interactive",
  },
  {
    method: "GET",
    path: "/api/v1/admin/users",
    summary: "List users",
    description: "All users with role, status, API-token permission, last sign-in and usage counts.",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "PATCH",
    path: "/api/v1/admin/users/{id}",
    summary: "Update a user",
    description: "Change role, enable/disable the account, or allow API-token generation.",
    tag: "Admin",
    scope: "admin",
    body: {
      type: "object",
      properties: {
        role: { type: "string", enum: ["admin", "member"] },
        status: { type: "string", enum: ["active", "disabled"] },
        can_create_api_keys: { type: "boolean" },
        full_name: { type: "string", nullable: true },
      },
    },
  },
  {
    method: "DELETE",
    path: "/api/v1/admin/users/{id}",
    summary: "Delete a user",
    description: "Removes the account and all of its data.",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "POST",
    path: "/api/v1/admin/users/{id}/reset-link",
    summary: "Generate a password-reset link",
    description: "No email is sent; share the returned link with the user. Valid for 2 days.",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "GET",
    path: "/api/v1/admin/invitations",
    summary: "List invitations",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "POST",
    path: "/api/v1/admin/invitations",
    summary: "Create an invitation link",
    description: "Returns a one-time link the invitee opens to set a password. No email is sent.",
    tag: "Admin",
    scope: "admin",
    body: {
      type: "object",
      required: ["email"],
      properties: {
        email: { type: "string", format: "email" },
        role: { type: "string", enum: ["admin", "member"] },
        can_create_api_keys: { type: "boolean" },
        expires_in_days: { type: "integer", minimum: 1, maximum: 90 },
        note: { type: "string" },
      },
    },
    example: { email: "new.user@example.com", role: "member", can_create_api_keys: true },
  },
  {
    method: "DELETE",
    path: "/api/v1/admin/invitations/{id}",
    summary: "Revoke an invitation",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "GET",
    path: "/api/v1/admin/connectors",
    summary: "Mail connector status",
    description: "Whether Gmail and Outlook OAuth clients are configured (in-app or via environment) and the redirect URIs to register.",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "PUT",
    path: "/api/v1/admin/connectors",
    summary: "Save Gmail / Outlook OAuth client",
    description: "Stores the client id and (encrypted) secret so users can connect mailboxes without any redeploy. Omit client_secret to keep the stored one.",
    tag: "Admin",
    scope: "admin",
    body: {
      type: "object",
      required: ["provider", "client_id"],
      properties: {
        provider: { type: "string", enum: ["google", "microsoft"] },
        client_id: { type: "string" },
        client_secret: { type: "string" },
        tenant: { type: "string", description: "Microsoft only: common, consumers, organizations or a tenant id" },
        enabled: { type: "boolean" },
      },
    },
  },
  {
    method: "DELETE",
    path: "/api/v1/admin/connectors/{provider}",
    summary: "Remove in-app OAuth client",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "GET",
    path: "/api/v1/admin/settings",
    summary: "Read workspace settings",
    tag: "Admin",
    scope: "admin",
  },
  {
    method: "PATCH",
    path: "/api/v1/admin/settings",
    summary: "Update workspace settings",
    description: "Self sign-up, platform AI availability, default API-token permission, invitation expiry.",
    tag: "Admin",
    scope: "admin",
    body: {
      type: "object",
      properties: {
        app_name: { type: "string" },
        allow_self_signup: { type: "boolean" },
        allow_platform_ai: { type: "boolean" },
        default_can_create_api_keys: { type: "boolean" },
        invitation_expiry_days: { type: "integer" },
      },
    },
  },
  {
    method: "GET",
    path: "/api/v1/openapi.json",
    summary: "OpenAPI 3.1 specification",
    tag: "Meta",
    scope: "public",
  },
  {
    method: "GET",
    path: "/api/health",
    summary: "Health check",
    tag: "Meta",
    scope: "public",
  },
];
